/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as ViewsRouteImport } from './routes/views'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdIssuesRouteImport } from './routes/projects/$projectId/issues'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsRoute = ViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => IssuesRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIssuesRoute = ProjectsProjectIdIssuesRouteImport.update({
  id: '/projects/$projectId/issues',
  path: '/projects/$projectId/issues',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox': typeof InboxRoute
  '/issues': typeof IssuesRouteWithChildren
  '/views': typeof ViewsRoute
  '/workspace': typeof WorkspaceRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox': typeof InboxRoute
  '/issues': typeof IssuesRouteWithChildren
  '/views': typeof ViewsRoute
  '/workspace': typeof WorkspaceRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox': typeof InboxRoute
  '/issues': typeof IssuesRouteWithChildren
  '/views': typeof ViewsRoute
  '/workspace': typeof WorkspaceRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/inbox'
    | '/issues'
    | '/views'
    | '/workspace'
    | '/issues/$issueId'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/inbox'
    | '/issues'
    | '/views'
    | '/workspace'
    | '/issues/$issueId'
    | '/projects/$projectId/issues'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/inbox'
    | '/issues'
    | '/views'
    | '/workspace'
    | '/issues/$issueId'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InboxRoute: typeof InboxRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  ViewsRoute: typeof ViewsRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ProjectsProjectIdIssuesRoute: typeof ProjectsProjectIdIssuesRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views': {
      id: '/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof ViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/issues': {
      id: '/projects/$projectId/issues'
      path: '/projects/$projectId/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof ProjectsProjectIdIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IssuesRouteChildren {
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIssueIdRoute: IssuesIssueIdRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InboxRoute: InboxRoute,
  IssuesRoute: IssuesRouteWithChildren,
  ViewsRoute: ViewsRoute,
  WorkspaceRoute: WorkspaceRoute,
  ProjectsProjectIdIssuesRoute: ProjectsProjectIdIssuesRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
