/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAboutRouteImport } from './routes/_authed/about'
import { Route as AuthedInboxRouteImport } from './routes/_authed/inbox'
import { Route as AuthedViewsRouteImport } from './routes/_authed/views'
import { Route as AuthedWorkspaceRouteImport } from './routes/_authed/workspace'
import { Route as AuthedIssuesIndexRouteImport } from './routes/_authed/issues/index'
import { Route as AuthedIssuesIssueIdRouteImport } from './routes/_authed/issues/$issueId'
import { Route as AuthedProjectsProjectIdIndexRouteImport } from './routes/_authed/projects/$projectId/index'
import { Route as AuthedProjectsProjectIdIssuesRouteImport } from './routes/_authed/projects/$projectId/issues'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAboutRoute = AuthedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInboxRoute = AuthedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedViewsRoute = AuthedViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedWorkspaceRoute = AuthedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIssuesIndexRoute = AuthedIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIssuesIssueIdRoute = AuthedIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProjectsProjectIdIndexRoute =
  AuthedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProjectsProjectIdIssuesRoute =
  AuthedProjectsProjectIdIssuesRouteImport.update({
    id: '/projects/$projectId/issues',
    path: '/projects/$projectId/issues',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/about': typeof AuthedAboutRoute
  '/inbox': typeof AuthedInboxRoute
  '/views': typeof AuthedViewsRoute
  '/workspace': typeof AuthedWorkspaceRoute
  '/issues/$issueId': typeof AuthedIssuesIssueIdRoute
  '/issues/': typeof AuthedIssuesIndexRoute
  '/projects/$projectId/issues': typeof AuthedProjectsProjectIdIssuesRoute
  '/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/about': typeof AuthedAboutRoute
  '/inbox': typeof AuthedInboxRoute
  '/views': typeof AuthedViewsRoute
  '/workspace': typeof AuthedWorkspaceRoute
  '/issues/$issueId': typeof AuthedIssuesIssueIdRoute
  '/issues': typeof AuthedIssuesIndexRoute
  '/projects/$projectId/issues': typeof AuthedProjectsProjectIdIssuesRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/_authed/about': typeof AuthedAboutRoute
  '/_authed/inbox': typeof AuthedInboxRoute
  '/_authed/views': typeof AuthedViewsRoute
  '/_authed/workspace': typeof AuthedWorkspaceRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/issues/$issueId': typeof AuthedIssuesIssueIdRoute
  '/_authed/issues/': typeof AuthedIssuesIndexRoute
  '/_authed/projects/$projectId/issues': typeof AuthedProjectsProjectIdIssuesRoute
  '/_authed/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/about'
    | '/inbox'
    | '/views'
    | '/workspace'
    | '/issues/$issueId'
    | '/issues/'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/about'
    | '/inbox'
    | '/views'
    | '/workspace'
    | '/issues/$issueId'
    | '/issues'
    | '/projects/$projectId/issues'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authed'
    | '/_auth/login'
    | '/_auth/setup'
    | '/_authed/about'
    | '/_authed/inbox'
    | '/_authed/views'
    | '/_authed/workspace'
    | '/_authed/'
    | '/_authed/issues/$issueId'
    | '/_authed/issues/'
    | '/_authed/projects/$projectId/issues'
    | '/_authed/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/about': {
      id: '/_authed/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthedAboutRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/inbox': {
      id: '/_authed/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedInboxRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/views': {
      id: '/_authed/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof AuthedViewsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/workspace': {
      id: '/_authed/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthedWorkspaceRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/issues/': {
      id: '/_authed/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthedIssuesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/issues/$issueId': {
      id: '/_authed/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof AuthedIssuesIssueIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/projects/$projectId/issues': {
      id: '/_authed/projects/$projectId/issues'
      path: '/projects/$projectId/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof AuthedProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedAboutRoute: typeof AuthedAboutRoute
  AuthedInboxRoute: typeof AuthedInboxRoute
  AuthedViewsRoute: typeof AuthedViewsRoute
  AuthedWorkspaceRoute: typeof AuthedWorkspaceRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedIssuesIssueIdRoute: typeof AuthedIssuesIssueIdRoute
  AuthedIssuesIndexRoute: typeof AuthedIssuesIndexRoute
  AuthedProjectsProjectIdIssuesRoute: typeof AuthedProjectsProjectIdIssuesRoute
  AuthedProjectsProjectIdIndexRoute: typeof AuthedProjectsProjectIdIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAboutRoute: AuthedAboutRoute,
  AuthedInboxRoute: AuthedInboxRoute,
  AuthedViewsRoute: AuthedViewsRoute,
  AuthedWorkspaceRoute: AuthedWorkspaceRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedIssuesIssueIdRoute: AuthedIssuesIssueIdRoute,
  AuthedIssuesIndexRoute: AuthedIssuesIndexRoute,
  AuthedProjectsProjectIdIssuesRoute: AuthedProjectsProjectIdIssuesRoute,
  AuthedProjectsProjectIdIndexRoute: AuthedProjectsProjectIdIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
